### ISSUE TITLE
Theme text file rename text overlaps...

### ISSUE THREAD

**Issue by MirceaMx** [nx-desktop/nx-kvantum-theme#5]
The text overlaps, strange behavior when trying to rename file + the edit cursor is not visible. (Cannot screenshot to show you)

**Comment by UriHerrera** [comment]
Please add screenshots or a video showing the problem and what version you have installed.

**Comment by MirceaMx** [comment]
I have manually installed the .deb (kvantum-theme-kvnomad_1.5.0_amd64.deb
<http://repo.nxos.org/development/pool/main/k/kvantum-theme-kvnomad/kvantum-theme-kvnomad_1.5.0_amd64.deb>
)

**Comment by UriHerrera** [comment]
Kvantum needs to be at version 0.10.7. The newer deb is here: http://repo.nxos.org/development/pool/main/k/kvantum/kvantum_0.10.7_amd64.deb

**Comment by MirceaMx** [comment]
I'm sorry to say but it still has issues (screenshot attached)

**Comment by MirceaMx** [comment]
LOL still an issue with version 14. Great distro (ironic). Will recommend write about it.

**Comment by UriHerrera** [comment]
The overlapping issue is related to a combination of the Qt version in use, Kvantum version and theme. The theme was fixed in version 1.5.0 as of now it doesn't present this issue anymore.

![](https://image.ibb.co/cG3wze/Screenshot_20180831_124658.png)
