### ISSUE TITLE
Nitrux Dark Theme Color Issues

### ISSUE THREAD

**Issue by Sarcasmo220** [nx-desktop/nx-kvantum-theme#6]
**Describe the bug**
In the when adding a connection type (in this case a VPN), the "Choose a Connection Type" dialog box has a list of different connection types, but the font of text is white and the background is white making it impossible to read.

**To Reproduce**
1. Go to  Connections - System Settings
2. Click on the "+" icon to add a connection
3. See error

**Expected behavior**
Background in the list should be dark

**Screenshots**
![Screenshot_20200713_115833](https://user-images.githubusercontent.com/68247163/87342600-6138b680-c500-11ea-8d39-803a18cb00fe.png)

**Desktop (please complete the following information):**
 - OS: Nitrux OS 1.3.0

**Comment by UriHerrera** [comment]
This seems to be an issue of the Kvantum dark theme.

**Comment by UriHerrera** [comment]
Fixed in https://github.com/nx-desktop/nx-plasma-look-and-feel/commit/d8981df27ffcc52c29f3ab6e5b38322c24abc798 and https://github.com/nx-desktop/nx-kvantum-theme/commit/a23632749d01d44d9826e7a61f37c7c2dba4f8db.
